name: Notify New Relic on Successful Workflow Completion

on:
  workflow_run:
    workflows: ["Long Running Workflow"]
    types:
      - completed

jobs:
  notify_new_relic_on_success:
    runs-on: ubuntu-latest
    steps:
      - name: Record start time
        id: start_time
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Your Actual Workflow Job
        run: |
          # Simulate some work or run your actual workflow steps
          sleep 100  # Replace this with actual steps

      - name: Record end time
        id: end_time
        run: echo "end_time=$(date +%s)" >> $GITHUB_ENV

      - name: Create JSON payload
        id: create_payload
        run: |
          duration=$(( ${{ env.end_time }} - ${{ env.start_time }} ))
          echo "Workflow duration: $duration seconds"
          
          # Create the JSON payload
          cat <<EOF > event_payload.json
          [
            {
              "eventType": "GitHubWorkflowSuccess",
              "repo": "${{ github.repository }}",
              "workflow": "${{ github.workflow }}",
              "duration": "$duration",
              "status": "success",
              "url": "${{ github.server_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "run_id": "${{ github.run_id }}",
              "run_number": "${{ github.run_number }}",
              "sha": "${{ github.sha }}",
              "ref": "${{ github.ref }}"
            }
          ]
          EOF

      - name: Notify New Relic on Success
        if: ${{ success() }}  # Ensure this step runs only if the workflow succeeds
        run: |
          # Gzip the payload and send it to New Relic
          gzip -c event_payload.json | curl -X POST -H "Content-Type: application/json" \
            -H "Api-Key: eu01xx9ddbdb162b1ed2a2f98b070fd1FFFFNRAL" \
            -H "Content-Encoding: gzip" \
            https://insights-collector.newrelic.com/v1/accounts/3398389/events \
            --data-binary @-

          # Check the response
          response_code=$?
          if [ $response_code -ne 0 ]; then
            echo "Error sending event to New Relic: $response_code"
            exit 1
          else
            echo "Event sent successfully to New Relic."
          fi
